//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CIDADES
    {
        public CIDADES()
        {
            this.MEDICOS = new HashSet<MEDICOS>();
        }
    
        public int ID_CIDADE { get; set; }
        public short ID_ESTADO { get; set; }
        public string CIDADE { get; set; }
    
        public virtual ICollection<MEDICOS> MEDICOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
    }
}
