//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESPECIALIDADES
    {
        public ESPECIALIDADES()
        {
            this.MEDICOS1 = new HashSet<MEDICOS>();
        }
    
        public short ID_ESPECIALIDADE { get; set; }
        public string ESPECIALIDADE { get; set; }
    
        public virtual ICollection<MEDICOS> MEDICOS1 { get; set; }
    }
}
