//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.CIDADES = new HashSet<CIDADES>();
        }
    
        public short ID_ESTADO { get; set; }
        public int ID_PAIS { get; set; }
        public string ESTADO { get; set; }
        public string SIGLA { get; set; }
    
        public virtual ICollection<CIDADES> CIDADES { get; set; }
        public virtual PAISES PAISES { get; set; }
    }
}
