//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEDICOS
    {
        public int ID_MEDICO { get; set; }
        public short ID_ESPECIALIDADE { get; set; }
        public string CRM { get; set; }
        public string NOME { get; set; }
        public string ENDERECO { get; set; }
        public string BAIRRO { get; set; }
        public int ID_CIDADE { get; set; }
        public string EMAIL { get; set; }
        public Nullable<bool> ATENDE_POR_CONVENIO { get; set; }
        public Nullable<bool> TEM_CLINICA { get; set; }
        public string WEB_SITE_BLOG { get; set; }
    
        public virtual CIDADES CIDADES { get; set; }
        public virtual ESPECIALIDADES ESPECIALIDADES1 { get; set; }
    }
}
