//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CadeMeuMedico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAISES
    {
        public PAISES()
        {
            this.ESTADOS = new HashSet<ESTADOS>();
        }
    
        public int ID_PAIS { get; set; }
        public string PAIS { get; set; }
    
        public virtual ICollection<ESTADOS> ESTADOS { get; set; }
    }
}
